# pg_hba.conf - правила аутентификации PostgreSQL

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Локальные подключения
local   all             all                                     trust

# IPv4 локальные подключения:
host    all             all             127.0.0.1/32            md5

# IPv6 локальные подключения:
host    all             all             ::1/128                 md5

# Удаленные подключения (ОСТОРОЖНО! Для продакшн используйте более строгие правила)
host    all             all             0.0.0.0/0               md5

# Подключения из Docker сети
host    all             all             172.16.0.0/12           md5
